-- Table structure for case studies board
CREATE TABLE IF NOT EXISTS pap_board_casestudies_en (
    no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    tmp1 VARCHAR(255) DEFAULT NULL,
    tmp2 VARCHAR(255) DEFAULT NULL,
    tmp3 VARCHAR(255) DEFAULT NULL,
    tmp4 VARCHAR(255) DEFAULT NULL,
    content MEDIUMTEXT,
    regDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    hit INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
